<?php
// Make a MySQL Connection
db_connect();

// Insert a row of information into the table "style_admin"
mysql_query("INSERT INTO style_admin 
(
BodyMarginLeft,
BodyColor,
BodyBackgroundColor,
BodyBackgroundRepeat,
BodyBackgroundAttachment,
BodyBackgroundPosition,
BodyHeight,

FullBackgroundColor,
FullBackgroundRepeat,
FullBackgroundAttachment,
FullBackgroundPosition,
FullColor,
FullMargin,
FullMinHeight,
FullWidth,

HFullBackgroundColor,
HFullBackgroundRepeat,
HFullBackgroundAttachment,
HFullBackgroundPosition,
HFullColor,
HFullWidth,

HFloatBackgroundColor,
HFloatBackgroundRepeat,
HFloatBackgroundAttachment,
HFloatBackgroundPosition,
HFloatColor,
HFloatFontFamily,
HFloataLinkTextDecoration,
HFloataVisitedDecoration,
HFloataHoverTextDecoration,
HFloataActiveTextDecoration,
HFloatMargin,
HFloatPadding,
HFloatWidth,

BFullBackgroundColor,
BFullBackgroundRepeat,
BFullBackgroundAttachment,
BFullBackgroundPosition,
BFullColor,
BFullWidth,

BFloatBackgroundColor,
BFloatBackgroundRepeat,
BFloatBackgroundAttachment,
BFloatBackgroundPosition,
BFloatColor,
BFloatMargin,
BFloatPadding,
BFloatWidth,

NavbarBackgroundColor,
NavbarBackgroundRepeat,
NavbarBackgroundAttachment,
NavbarBackgroundPosition,
NavbarColor,
NavbarFontFamily,
NavbaraLinkTextDecoration,
NavbaraVisitedDecoration,
NavbaraHoverTextDecoration,
NavbaraActiveTextDecoration,
NavbarBorderTopThickness,
NavbarBorderTopStyle,
NavbarBorderTopColor,
NavbarBorderRightThickness,
NavbarBorderRightStyle,
NavbarBorderRightColor,
NavbarBorderBottomThickness,
NavbarBorderBottomStyle,
NavbarBorderBottomColor,
NavbarBorderLeftThickness,
NavbarBorderLeftStyle,
NavbarBorderLeftColor,
NavbarPadding,
NavbarWidth,
NavbarFloat,

PageBackgroundColor,
PageBackgroundRepeat,
PageBackgroundAttachment,
PageBackgroundPosition,
PageColor,
PageBorderTopThickness,
PageBorderTopStyle,
PageBorderTopColor,
PageBorderRightThickness,
PageBorderRightStyle,
PageBorderRightColor,
PageBorderBottomThickness,
PageBorderBottomStyle,
PageBorderBottomColor,
PageBorderLeftThickness,
PageBorderLeftStyle,
PageBorderLeftColor,
PagePadding,
PageWidth,
PageFloat,

NavbarRightBackgroundColor,
NavbarRightBackgroundRepeat,
NavbarRightBackgroundAttachment,
NavbarRightBackgroundPosition,
NavbarRightColor,
NavbarRightBorderTopThickness,
NavbarRightBorderTopStyle,
NavbarRightBorderTopColor,
NavbarRightBorderRightThickness,
NavbarRightBorderRightStyle,
NavbarRightBorderRightColor,
NavbarRightBorderBottomThickness,
NavbarRightBorderBottomStyle,
NavbarRightBorderBottomColor,
NavbarRightBorderLeftThickness,
NavbarRightBorderLeftStyle,
NavbarRightBorderLeftColor,
NavbarRightPadding,
NavbarRightWidth,
NavbarRightDisplay,
NavbarRightFloat,

FFullBackgroundColor,
FFullBackgroundRepeat,
FFullBackgroundAttachment,
FFullBackgroundPosition,
FFullColor,
FFullWidth,

FFloatBackgroundColor,
FFloatBackgroundRepeat,
FFloatBackgroundAttachment,
FFloatBackgroundPosition,
FFloatColor,
FFloatBorderTopThickness,
FFloatBorderTopStyle,
FFloatBorderTopColor,
FFloatBorderRightThickness,
FFloatBorderRightStyle,
FFloatBorderRightColor,
FFloatBorderBottomThickness,
FFloatBorderBottomStyle,
FFloatBorderBottomColor,
FFloatBorderLeftThickness,
FFloatBorderLeftStyle,
FFloatBorderLeftColor,
FFloatPadding,
FFloatMargin,
FFloatWidth,
FFloatDisplay,

LinksBackgroundColor,
LinksBackgroundRepeat,
LinksBackgroundAttachment,
LinksBackgroundPosition,
LinksColor,
LinksBorderTopThickness,
LinksBorderTopStyle,
LinksBorderTopColor,
LinksBorderRightThickness,
LinksBorderRightStyle,
LinksBorderRightColor,
LinksBorderBottomThickness,
LinksBorderBottomStyle,
LinksBorderBottomColor,
LinksBorderLeftThickness,
LinksBorderLeftStyle,
LinksBorderLeftColor,
LinksPadding,
LinksMargin,
LinksWidth,
LinksDisplay

)
VALUES
(
'0px',
'#000000',
'#ffffff',
'repeat-x',
'scroll',
'left top',
'100%',

'#ffffff',
'repeat-x',
'scroll',
'left top',
'#000000',
'auto',
'100%',
'95%',

'#ffffff',
'repeat-x',
'scroll',
'left top',
'#000000',
'95%',

'#ffffff',
'repeat-x',
'scroll',
'left top',
'#000000',
'arial, tahoma, sans-serif',
'none',
'none',
'underline',
'underline',
'auto',
'5px',
'1000px',

'#ffffff',
'repeat-x',
'scroll',
'left top',
'#000000',
'95%',

'#ffffff',
'repeat-x',
'scroll',
'left top',
'#000000',
'auto',
'5px',
'1000px',

'#ffffff',
'repeat-x',
'scroll',
'left top',
'#000000',
'arial, tahoma, sans-serif',
'none',
'none',
'underline',
'underline',
'1px',
'solid',
'#000000',
'1px',
'solid',
'#000000',
'1px',
'solid',
'#000000',
'1px',
'solid',
'#000000',
'5px',
'15%',
'left',

'#ffffff',
'repeat-x',
'scroll',
'left top',
'#000000',
'1px',
'solid',
'#000000',
'1px',
'solid',
'#000000',
'1px',
'solid',
'#000000',
'1px',
'solid',
'#000000',
'5px',
'80%',
'right',

'#ffffff',
'repeat-x',
'scroll',
'left top',
'#000000',
'2px',
'solid',
'#000000',
'2px',
'solid',
'#000000',
'2px',
'solid',
'#000000',
'2px',
'solid',
'#000000',
'5px',
'258px',
'none',
'right',

'#ffffff',
'repeat-x',
'scroll',
'left top',
'#000000',
'95%',

'#ffffff',
'repeat-x',
'scroll',
'left top',
'#000000',
'2px',
'solid',
'#000000',
'2px',
'solid',
'#000000',
'2px',
'solid',
'#000000',
'2px',
'solid',
'#000000',
'5px',
'auto',
'1000px',
'none',

'#ffffff',
'repeat-x',
'scroll',
'left top',
'#000000',
'2px',
'solid',
'#000000',
'2px',
'solid',
'#000000',
'2px',
'solid',
'#000000',
'2px',
'solid',
'#000000',
'5px',
'auto',
'1000px',
'none'

) ") 
or die(mysql_error());  

echo "Added default values to style_admin table!";

?>
